INSTALL = install
PREFIX = /usr/local
PKGCONFIGDIR = $(PREFIX)/lib/pkgconfig
FSODATADIR = $(PREFIX)/share/freesmartphone

SUBDIRS := \
  org.freesmartphone \
  org.freesmartphone.Data \
  org.freesmartphone.Device \
  org.freesmartphone.Phone \
  org.freesmartphone.Usage \
  org.freesmartphone.Events \
  org.freesmartphone.PIM \
  org.freedesktop.Gypsy \
  org.freesmartphone.GSM \
  org.freesmartphone.Preferences \
  org.freesmartphone.Network \
  org.freesmartphone.Notification \
  org.freesmartphone.Time \
  org.freesmartphone.MusicPlayer

.PHONY: all clean check docs xml install

all:
	@for i in $(SUBDIRS); do (cd $$i && $(MAKE) all docs xml) || exit 1 ; done

clean:
	@for i in $(SUBDIRS); do (cd $$i && $(MAKE) clean) || exit 1 ; done

check:
	@for i in $(SUBDIRS); do (cd $$i && $(MAKE) check) || exit 1 ; done

docs:
	@for i in $(SUBDIRS); do (cd $$i && $(MAKE) docs) || exit 1 ; done

xml:
	for i in $(SUBDIRS); do (cd $$i && $(MAKE) xml) || exit 1 ; done

install: xml
	$(INSTALL) -d $(FSODATADIR)
	for i in xml/*.xml; do $(INSTALL) -m 0644 $$i $(FSODATADIR)/$$i; done
	$(INSTALL) -d $(PKGCONFIGDIR)

