files = \
  org.freesmartphone.Device.Audio.xml \
  org.freesmartphone.Device.Display.xml \
  org.freesmartphone.Device.LED.xml \
  org.freesmartphone.Device.Input.xml \
  org.freesmartphone.Device.IdleNotifier.xml \
  org.freesmartphone.Device.PowerControl.xml \
  org.freesmartphone.Device.PowerSupply.xml \
  org.freesmartphone.Device.RealtimeClock.xml

include ../tools/rules.mk
