files = \
  org.freesmartphone.Device.Audio.xml \
  org.freesmartphone.Device.Display.xml \
  org.freesmartphone.Device.Input.xml \
  org.freesmartphone.Device.IdleNotifier.xml \

include ../tools/rules.mk
