files = \
  org.freesmartphone.PIM.Source.xml \
  org.freesmartphone.PIM.Sources.xml \
  org.freesmartphone.PIM.Contact.xml \
  org.freesmartphone.PIM.Contacts.xml \
  org.freesmartphone.PIM.ContactQuery.xml \
  org.freesmartphone.PIM.Message.xml \
  org.freesmartphone.PIM.Messages.xml \
  org.freesmartphone.PIM.MessageQuery.xml \
  org.freesmartphone.PIM.MessageFolder.xml

include ../tools/rules.mk
